name: Deploy Camera Tutorials HTML

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        run: |
          uv python install 3.11

      - name: Install dependencies
        run: |
          uv sync --all-extras --dev

      - name: Build Sphinx documentation
        run: |
          uv run make html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/html
